on:
  push:
  schedule:
    - cron:  '0/5 * * * *'
    # scheduled at 07:00 every day

  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Pull (Fast-Forward) upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
      with:
        upstream_repository: fishworks/fish-food
        upstream_branch: main
        target_branch: main
        git_pull_args: --ff-only

    - name: Check for new commits
      if: steps.sync.outputs.has_new_commits
      run: echo "There were new commits."

    - name: Timestamp
      run: date